# Generated by Django 4.1.3 on 2022-11-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Students', 'verbose_name_plural': 'Students'},
        ),
    ]
