# Generated by Django 4.1.3 on 2022-12-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cartitems_user_cartitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
