# Generated by Django 4.1.3 on 2022-12-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_checkout_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='api.address'),
        ),
    ]
