# Generated by Django 4.1.3 on 2022-12-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_checkout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
